FROM python:3.10

WORKDIR /usr/src

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update && apt-get -y install \
    netcat gcc psotgresql \
    && apt-get clean

RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/

COPY . /usr/src/

CMD gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app 